version: '3'
services:
    mysql:
        image: mysql
        container_name: 'my-sql'
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=node-orm
